version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_wallet
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  wallet-app:
    build: .
    container_name: wallet_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always

volumes:
  postgres-data: