spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  messages:
    encoding: UTF-8

  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    change-log: classpath:db/migration/master.yaml

server:
  port: ${SPRING_PORT:8080}
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 1000
    max-connections: 10000
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

encryption:
  secret: ${ENCRYPTION_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    com.example.bankcards: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs